name: BasePlugin
version: ${project.version}
main: de.marvinleiers.baseplugin.BasePlugin
api-version: 1.16
authors: [ Marvin_Leiers, Marvin2k0 ]
website: https://www.marvinleiers.de

commands:
  base:
